name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Test env vars for python
        env:
          SLACK_HLC_TOKEN: '${{ secrets.SLACK_HLC_TOKEN }}'
        run: python -c "import os; print(os.environ.get('SLACK_HLC_TOKEN'))"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk
      - name: execute py script # run file
        env:  
          SLACK_HLC_TOKEN: '${{ secrets.SLACK_HLC_TOKEN }}'
        run: |
          python SendMessage.py