name: Run SendMessage.py
run-name: ${{ github.actor }} just ran ${{ github.workflow }} on ${{ github.repository }}
on:
  schedule:
  #run a cron job every 5 minutes
  - cron: '*/5 * * * *'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk
      - name: execute SendMessage.py script # run file
        env:  
          SLACK_HLC_TOKEN: '${{ secrets.SLACK_HLC_TOKEN }}'
        run: |
          python SendMessage.py