name: Run SendMessage.py Every Friday at 16:00 UTC
run-name: New ${{ github.workflow }} event
on:
  schedule:
  # Run a cron job every Friday at 4pm UTC
  - cron: '0 16 * * 5'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk
      - name: execute SendMessage.py script
        env:  
          SLACK_HLC_TOKEN: '${{ secrets.SLACK_HLC_TOKEN }}'
        run: |
          python SendMessage.py